/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee;
import javax.swing.JFrame;
import java.sql.SQLException;
import java.util.regex.Pattern;

import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Create_Acc extends javax.swing.JFrame {

    public Create_Acc() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_AG = new javax.swing.JTextField();
        jButton_Cancel = new javax.swing.JButton();
        jButton_Register_ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_FN = new javax.swing.JTextField();
        jTextField_LN = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_EI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_AD = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jPasswordField_PD = new javax.swing.JPasswordField();
        jTextField_BD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1min = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 148, 6));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manager Registeration Form");

        jLabel1close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1close.setText("X");
        jLabel1close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1closeMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("BirthDate");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Age");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 80, -1));

        jTextField_AG.setBackground(new java.awt.Color(153, 153, 153));
        jTextField_AG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_AG.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jTextField_AG, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 330, -1));

        jButton_Cancel.setBackground(new java.awt.Color(255, 0, 0));
        jButton_Cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 116, 49));

        jButton_Register_.setBackground(new java.awt.Color(34, 167, 240));
        jButton_Register_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Register_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Register_.setText("Register");
        jButton_Register_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Register_MouseClicked(evt);
            }
        });
        jButton_Register_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Register_ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_Register_, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 116, 49));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 282, 312, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Click Here to Login");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setText("First Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 109, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("Last Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 109, -1));

        jTextField_FN.setBackground(new java.awt.Color(153, 153, 153));
        jTextField_FN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_FN.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_FN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FNActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_FN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 330, -1));

        jTextField_LN.setBackground(new java.awt.Color(153, 153, 153));
        jTextField_LN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_LN.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_LN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LNActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_LN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 330, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 240, 241));
        jLabel10.setText("Address");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 109, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(236, 240, 241));
        jLabel11.setText("Email Id");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 110, -1));

        jTextField_EI.setBackground(new java.awt.Color(153, 153, 153));
        jTextField_EI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_EI.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_EI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EIActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_EI, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 330, -1));

        jTextArea_AD.setBackground(new java.awt.Color(153, 153, 153));
        jTextArea_AD.setColumns(20);
        jTextArea_AD.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea_AD.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_AD.setRows(5);
        jTextArea_AD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextArea_AD);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 330, 90));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(236, 240, 241));
        jLabel12.setText("Password");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 109, -1));

        jPasswordField_PD.setBackground(new java.awt.Color(153, 153, 153));
        jPasswordField_PD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPasswordField_PD.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField_PD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_PDActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordField_PD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 330, -1));

        jTextField_BD.setBackground(new java.awt.Color(153, 153, 153));
        jTextField_BD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_BD.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jTextField_BD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 330, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("(YYYY-MM-DD)");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel1min.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1min.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1min.setText("-");
        jLabel1min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1minMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1min)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1close)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1close)
                    .addComponent(jLabel1min)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1closeMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        login rgf = new login();
        this.setVisible(false);
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jTextField_LNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LNActionPerformed

    private void jTextField_EIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EIActionPerformed
if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", jTextField_EI.getText()))) 
{
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EIActionPerformed

    private void jLabel1minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1minMouseClicked
      this.setState(JFrame.ICONIFIED);       
    }//GEN-LAST:event_jLabel1minMouseClicked

    private void jButton_Register_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Register_MouseClicked
   
    }//GEN-LAST:event_jButton_Register_MouseClicked

    private void jButton_Register_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Register_ActionPerformed
        String fname = jTextField_FN.getText();
        String lname = jTextField_LN.getText();
        String email = jTextField_EI.getText();
        String pass = String.valueOf(jPasswordField_PD.getPassword());
        String bdate = jTextField_BD.getText();
        String address = jTextArea_AD.getText();
        String age = jTextField_AG.getText();
        
        
        conn cc = new conn();
       String q = "insert into registration values('"+fname+"','"+lname+"','"+email+"','"+bdate+"','"+address+"','"+age+"')";
       String z = "insert into forgotpassjava values('"+email+"','"+pass+"')";
       
       try {
        if(fname.equals("")){
            JOptionPane.showMessageDialog(null,"Firstname cannot be empty");
        }
        else if(lname.equals("")){
            JOptionPane.showMessageDialog(null,"Lastname cannot be empty");
        }
        else if(email.equals("")){
            JOptionPane.showMessageDialog(null,"Email cannot be empty");
        }
        else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email))) 
        {
            JOptionPane.showMessageDialog(null, "Please enter a valid email");
            }
        else if(pass.equals("")){
            JOptionPane.showMessageDialog(null,"Password cannot be empty");
        }
        else if(bdate.equals("")){
            JOptionPane.showMessageDialog(null,"Birth Date cannot be empty");
        }
        else if(address.equals("")){
            JOptionPane.showMessageDialog(null,"Address cannot be empty");
        }
        else if(age.equals("")){
            JOptionPane.showMessageDialog(null,"Age cannot be empty");
        }
        else{       
            cc.s.executeUpdate(q);
            cc.s.executeUpdate(z);
            JOptionPane.showMessageDialog(null,"Data Registered Successfully");
            }
       } catch(SQLException ex){
           ex.printStackTrace();
       }
    }//GEN-LAST:event_jButton_Register_ActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        // TODO add your handling code here:
        login rgf = new login();
        this.setVisible(false);
        rgf.setVisible(true);
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jPasswordField_PDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_PDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_PDActionPerformed

    private void jTextField_FNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_Acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_Acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_Acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_Acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_Acc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Register_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel1close;
    private javax.swing.JLabel jLabel1min;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_PD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_AD;
    private javax.swing.JTextField jTextField_AG;
    private javax.swing.JTextField jTextField_BD;
    private javax.swing.JTextField jTextField_EI;
    private javax.swing.JTextField jTextField_FN;
    private javax.swing.JTextField jTextField_LN;
    // End of variables declaration//GEN-END:variables
}
